<a href="https://colab.research.google.com/github/Sarinda251/CAP_4630/blob/master/MultiplyMatrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Sarinda Samarasinghe

#HW1: Multiply Matrices

multiply_matrices takes as input a list of numpy arrays and outputs their product if it is possible.

If two matrices in the list are incompatible, the first pair is printed in an error message and an empty list is returned. The matrices in the error message are 0-indexed.



**Matrix Compatibility**

Given an \\(m \times n\\) matrix \\(A\\), and a \\(p \times q\\) matrix \\(B\\), \\(A\\) and \\(B\\) are compatible if \\(n = p\\). 

\begin{equation*}
A_{m,n} = 
\begin{Bmatrix}
a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
\vdots  & \vdots  & \ddots & \vdots  \\
a_{m,1} & a_{m,2} & \cdots & a_{m,n} 
\end{Bmatrix}
, B_{m,n} = 
\begin{Bmatrix}
b_{1,1} & b_{1,2} & \cdots & b_{1,q} \\
b_{2,1} & b_{2,2} & \cdots & b_{2,q} \\
\vdots  & \vdots  & \ddots & \vdots  \\
b_{p,1} & b_{p,2} & \cdots & b_{p,q} 
\end{Bmatrix}
\end{equation*}


The result of their multiplication is a \\(m \times q\\) matrix:

\begin{equation*}
A \times B = 
\begin{Bmatrix}
c_{1,1} & c_{1,2} & \cdots & c_{1,p} \\
c_{2,1} & c_{2,2} & \cdots & c_{2,p} \\
\vdots  & \vdots  & \ddots & \vdots  \\
c_{c,1} & c_{m,2} & \cdots & c_{m,p} 
\end{Bmatrix}
\end{equation*}

##Code

In [0]:
import numpy as np

def multiply_matrices(array_list):
  # sol stores the first matrix
  sol = array_list[0]

  # iterates through the rest of the list
  i = 1
  while i < len(array_list):
    # sol accumulates the multiplications if legal, otherwise exception is caught
    try:
      sol = sol.dot(array_list[i])
    except ValueError:
      print("Error: matrices " + str(i-1) + " and " + str(i) + " are incompatible for multiplication")
      return []
    i = i+1
  return sol

##Testing the function

**Standard**

In [39]:
A = [[2,3], [4,6]]
B = [[2,1], [7,8]]
input = [np.array(A),np.array(B)]
multiply_matrices(input)

array([[25, 26],
       [50, 52]])

**Longer List**


The output does not change, since the additional entry is the identity matrix

In [38]:
A = [[2,3], [4,6]]
B = [[2,1], [7,8]]
C = [[1,0], [0,1]]
input = [np.array(A),np.array(B),np.array(C)]
multiply_matrices(input)

array([[25, 26],
       [50, 52]])

**Error Message**

Incompatible arrays are 0-indexed

In [37]:
A = [[2,3], [4,6]]
B = [[2,1], [7,8], [0,0]]
C = [[1,0], [0,1]]
input = [np.array(A),np.array(B),np.array(C)]
multiply_matrices(input)

Error: matrices 0 and 1 are incompatible for multiplication


[]

**Edge Case**

If the list has only 1 matrix, it returns that matrix

In [35]:
A = [[2,3], [4,6]]
input = [np.array(A)]
multiply_matrices(input)

array([[2, 3],
       [4, 6]])