<a href="https://colab.research.google.com/github/Sarinda251/CAP_4630/blob/master/HW_4_1_and_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Homework 4, Problem 1

###Using only numpy, implement the function conv2d. It takes as input input_mat and kernel_mat and outputs output_mat. All variables are square matrices. It should compute the convolution of input_mat with the kernel kernel_mat using valid padding.



## Code

In [0]:
import numpy as np

def conv2d(input_mat, kernel_mat):

  # check if matrices are square
  if(input_mat.shape[0] != input_mat.shape[1]):
    print("Error: input matrix is not square")
    return []
  if(kernel_mat.shape[0] != kernel_mat.shape[1]):
    print("Error: kernel matrix is not square")
    return []

  n = input_mat.shape[0]
  f = kernel_mat.shape[0]

  if(f > n):
    print("Error: kernel matrix is too big")
    return []

  output_mat = np.zeros((n-f+1, n-f+1))

  # rotate kernel
  kernel_mat = np.flip(kernel_mat, 0)
  kernel_mat = np.flip(kernel_mat, 1)
  print(input_mat)
  print(kernel_mat)
  
  # apply filter
  for x in range(n-f+1):
    for y in range(n-f+1):
      for i in range(f):
        for j in range(f):
          output_mat[x][y] += input_mat[x+i][y+j] * kernel_mat[i][j]
  
  print(output_mat)
  return output_mat

## Test Cases


In [2]:
from scipy import signal
import numpy as np

input_mat = []
kernel_mat = []
expected_mat = []

# test case 1
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                       [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                                [4, 2, 4],
                                [2, 4, 2]]))

# test case 2
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0], [0, 1]]))
expected_mat.append(np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]]))


# test case 3
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, -1],
                       [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], [-1,  1, -1],[ 0, -1,  1]]))


# test case 4
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# test case 5 - should either through an error, or return empty matrix
input_mat.append(np.array([[1, -1],
                       [-1, 0]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append([])



for i in range(len(input_mat)):
  # uncomment line for student code testing
  output_mat = conv2d(input_mat[i], kernel_mat[i])

  print(output_mat)
  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!\n")
  else:
    print("Incorrect output!\n")


[[1 2 1 2]
 [2 1 2 1]
 [1 2 1 2]
 [2 1 2 1]]
[[1 0]
 [0 1]]
[[2. 4. 2.]
 [4. 2. 4.]
 [2. 4. 2.]]
[[2. 4. 2.]
 [4. 2. 4.]
 [2. 4. 2.]]
Correct output!

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1 0]
 [0 1]]
[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
Correct output!

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[ 0 -1]
 [-1  1]]
[[ 1. -1.  0.]
 [-1.  1. -1.]
 [ 0. -1.  1.]]
[[ 1. -1.  0.]
 [-1.  1. -1.]
 [ 0. -1.  1.]]
Correct output!

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[4.]]
[[4.]]
Correct output!

Error: kernel matrix is too big
[]
Correct output!



#Homework 4, Problem 2

###Using only numpy, implement the function maxpooling2d. It takes as input input_mat and s and outputs output_mat. The variables input_mat and output_mat are square matrices and s is an integer. It should compute the maxpooling operation on input_mat using window of shape s times s.

## Code

In [0]:
def maxpooling2d(input_mat, s):
  rows = input_mat.shape[0]
  cols = input_mat.shape[1]
  while(rows > cols):
    input_mat = np.column_stack((input_mat, np.zeros(rows)))
    cols += 1
  while(rows < cols):
    input_mat = np.vstack((input_mat, np.zeros(cols)))
    rows += 1

  if(rows % s != 0):
    print("Error: input array does not divide evenly into window size")
    return []

  output_mat = np.zeros((rows//s, rows//s))

  for x in range(0, cols, s):
    for y in range(0, rows, s):
      output_mat[x//s][y//s] = input_mat[x][y]
      for i in range(s):
        for j in range(s):
          output_mat[x//s][y//s] = max(output_mat[x//s][y//s],input_mat[x+i][y+j]) 

  print(input_mat)
  print(output_mat)
  return output_mat


## Test Cases

In [4]:
import skimage.measure

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])


for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])

  print(output_mat)
  #print(expected_mat[i])

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")


[[1 2 1 2]
 [2 4 2 1]
 [1 2 4 2]
 [2 1 2 1]]
[[4. 2.]
 [2. 4.]]
[[4. 2.]
 [2. 4.]]
Correct output!
[[1. 2. 1. 2. 4. 5.]
 [2. 4. 2. 1. 0. 3.]
 [1. 2. 4. 2. 4. 5.]
 [2. 1. 2. 1. 2. 1.]
 [1. 1. 2. 3. 1. 2.]
 [0. 0. 0. 0. 0. 0.]]
[[4. 2. 5.]
 [2. 4. 5.]
 [1. 3. 2.]]
[[4. 2. 5.]
 [2. 4. 5.]
 [1. 3. 2.]]
Correct output!
